import 'dart:io';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:peaklog/features/calendar/share/day_capture_sheet.dart';
import 'package:peaklog/l10n/app_localizations.dart';
import 'package:peaklog/l10n/app_localizations_en.dart';

// Minimal valid 1x1 red PNG so Image.memory can decode it without needing
// the real generated share image.
final _tinyPng = Uint8List.fromList([
  137, 80, 78, 71, 13, 10, 26, 10, 0, 0, 0, 13, 73, 72, 68, 82, 0, 0, 0, 1, 0,
  0, 0, 1, 8, 6, 0, 0, 0, 31, 21, 196, 137, 0, 0, 0, 13, 73, 68, 65, 84, 120,
  156, 99, 248, 207, 192, 240, 31, 0, 5, 0, 1, 255, 137, 153, 61, 29, 0, 0, 0,
  0, 73, 69, 78, 68, 174, 66, 96, 130,
]);

const _pathProviderChannel = MethodChannel('plugins.flutter.io/path_provider');
const _galChannel = MethodChannel('gal');

void main() {
  late Directory tempDir;
  late List<MethodCall> galCalls;

  setUp(() {
    tempDir = Directory.systemTemp.createTempSync('day_capture_sheet_test');
    galCalls = [];

    TestDefaultBinaryMessengerBinding.instance.defaultBinaryMessenger
        .setMockMethodCallHandler(_pathProviderChannel, (call) async {
      if (call.method == 'getTemporaryDirectory') return tempDir.path;
      return null;
    });

    TestDefaultBinaryMessengerBinding.instance.defaultBinaryMessenger
        .setMockMethodCallHandler(_galChannel, (call) async {
      galCalls.add(call);
      return null;
    });
  });

  tearDown(() {
    TestDefaultBinaryMessengerBinding.instance.defaultBinaryMessenger
        .setMockMethodCallHandler(_pathProviderChannel, null);
    TestDefaultBinaryMessengerBinding.instance.defaultBinaryMessenger
        .setMockMethodCallHandler(_galChannel, null);
    tempDir.deleteSync(recursive: true);
  });

  Future<void> pumpSheet(WidgetTester tester) async {
    await tester.pumpWidget(MaterialApp(
      localizationsDelegates: AppLocalizations.localizationsDelegates,
      supportedLocales: AppLocalizations.supportedLocales,
      home: Scaffold(
        body: DayCaptureSheet(imageBytes: _tinyPng, fileNamePrefix: 'peaklog_day_share_'),
      ),
    ));
    await tester.pumpAndSettle();
  }

  List<MethodCall> putImageCalls() =>
      galCalls.where((c) => c.method == 'putImage').toList();

  testWidgets('showing the sheet does not save — no gal.putImage call', (tester) async {
    await pumpSheet(tester);
    expect(galCalls, isEmpty);
  });

  testWidgets('tapping Save calls gal.putImage exactly once, with the exact generated bytes',
      (tester) async {
    await pumpSheet(tester);

    // Not pumpAndSettle: the Save button shows an indeterminate spinner
    // while saving, which schedules frames forever and never "settles".
    // The tap (and the real File I/O it triggers inside _save()) must run
    // inside runAsync so its awaits are actually serviced.
    await tester.runAsync(() async {
      await tester.tap(find.text('Save'));
      await Future<void>.delayed(const Duration(milliseconds: 100));
    });
    await tester.pump();

    // gal internally requests photo-library access before writing; filter
    // to the actual save call.
    final calls = putImageCalls();
    expect(calls, hasLength(1));
    final path = calls.single.arguments['path'] as String;
    expect(File(path).readAsBytesSync(), _tinyPng);
  });

  testWidgets(
      'after a successful save, the button alone shows the success confirmation — '
      'no separate/duplicate snackbar', (tester) async {
    await pumpSheet(tester);

    await tester.runAsync(() async {
      await tester.tap(find.text('Save'));
      await Future<void>.delayed(const Duration(milliseconds: 100));
    });
    await tester.pump();

    // The in-sheet button is the single source of save-success feedback —
    // exactly one match means no separate SnackBar is also showing the
    // same text (a SnackBar queued while this sheet is open can end up
    // hidden behind it and only appear once the sheet closes, reading as
    // duplicate confirmation).
    expect(find.text(AppLocalizationsEn().savedToPhotos), findsOneWidget);
    expect(find.byIcon(Icons.check), findsOneWidget);
  });

  testWidgets(
      'duplicate Save taps while a save is in flight only trigger one gal.putImage call',
      (tester) async {
    await pumpSheet(tester);

    await tester.runAsync(() async {
      // No pump between taps: the widget tree hasn't rebuilt yet, so both
      // taps hit the same button — the in-flight guard inside _save()
      // itself (not just the disabled-button styling) must reject the
      // second call.
      await tester.tap(find.text('Save'));
      await tester.tap(find.text('Save'));
      await Future<void>.delayed(const Duration(milliseconds: 100));
    });
    await tester.pump();

    expect(putImageCalls(), hasLength(1));
  });

  testWidgets('tapping Cancel dismisses without calling gal.putImage', (tester) async {
    await pumpSheet(tester);

    await tester.tap(find.text('Cancel'));
    await tester.pumpAndSettle();

    expect(galCalls, isEmpty);
  });
}
